-- MySQL Script generated by MySQL Workbench
-- Fri Jun 13 12:30:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e_commerce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e_commerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_commerce_db` DEFAULT CHARACTER SET utf8 ;
USE `e_commerce_db` ;

-- -----------------------------------------------------
-- Table `e_commerce_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_db`.`customers` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(100) NOT NULL,
  `customer_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_email_UNIQUE` (`customer_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_db`.`orders` (
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `order_amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK_customer_orders_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `FK_customer_orders`
    FOREIGN KEY (`customer_id`)
    REFERENCES `e_commerce_db`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
